### ISSUE TITLE
Resurrection

### ISSUE THREAD

**Issue by Jackhein** [Miorey/TrinityCore#19]
Can't resurrect people when spirit has been released.

This happens only when the user don't share the same mapID.
https://github.com/TrinityCore/TrinityCore/issues/22762

**Comment by Miorey** [comment]
This seems to be fixed: https://github.com/TrinityCore/TrinityCore/issues/23529 
On our server is not working I will investigate

**Comment by Miorey** [comment]
To reproduce this bug test it by trying to resurrect someone dead in a dungeon who release his soule.
